### ISSUE TITLE
Some training problem

### ISSUE THREAD

**Issue by Justsoso-J** [ac20/EnsembleEdgeWeightsHSI#1]
When I run "Evaluate_RandomWalk. py", the following error is prompted. How can I solve it? Thank you.
"ModuleNotFoundError: No module named 'matlab.engine'; 'matlab' is not a package"
![image](https://user-images.githubusercontent.com/77256538/192703622-ede763fe-78a2-4454-8638-439f4d5cd9bd.png)

**Comment by ac20** [comment]
We follow the official MATLAB documentation for installing the matlab engine for python. Details are [here](https://www.mathworks.com/help/matlab/matlab-engine-for-python.html).
